name: Master Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup environment variables
        run: echo "C_INCLUDE_PATH=$JAVA_HOME/include:$JAVA_HOME/include/darwin" >> $GITHUB_ENV

      - name: Run build
        run: ./gradlew build
