name: Release

on:
  workflow_dispatch:
    inputs:
      versionStrategy:
        description: 'The version increment strategy'
        default: Minor
        required: true
        type: choice
        options:
          - Prerelease
          - Patch
          - Minor
          - Major
jobs:
  create-tag:
    runs-on: macos-15
    outputs:
      tag: ${{ steps.post-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get pre-tag version
        run: ./gradlew currentVersion

      - name: Create tag
        run: |
          ./gradlew release \
            -Prelease.versionIncrementer=increment${{ github.event.inputs.versionStrategy }} \
            -Prelease.customUsername=${{ github.actor }} \
            -Prelease.customPassword=${{ github.token }}

      - name: Get tagged version
        id: post-tag
        run: echo "::set-output name=tag::v$(./gradlew cV -Prelease.quiet -q)"

  publish-artifacts:
    needs: [ create-tag ]
    runs-on: macos-15
    steps:
      - name: Checkout tag
        uses: actions/checkout@v2
        with:
          ref: ${{needs.create-tag.outputs.tag}}

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup environment variables
        run: echo "C_INCLUDE_PATH=$JAVA_HOME/include:$JAVA_HOME/include/darwin" >> $GITHUB_ENV

      - name: Build artifacts
        run: ./gradlew clean build -x test -x check

      - name: Stage artifacts to local directory
        run: ./gradlew publish

      - name: Deploy and release
        run: ./gradlew jreleaserFullRelease
        env:
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
